### ISSUE TITLE
Update the order of our data points

### ISSUE THREAD

**Issue by rachelng** [Shopify/polaris-viz#1409]
## Feature request summary
Update the order of our data points in Polaris Viz. The primary data point should always come first within a graph, tooltip and legend. The comparison should be secondary. The time frame for the x-axis should use the time frame that covers both data points. 

## Rationale
The comparison line in Polaris Viz is ordered first in the line series for our data viz and affects the order in our legends and tooltips. The primary line should come before the comparison. 

<img width="600" alt="Screen Shot 2022-10-25 at 11 35 40 AM" src="https://user-images.githubusercontent.com/6186705/197854344-c0c62c1f-22ae-49dd-ad5d-1f67022fae0e.png">

Because of this, when the data for `today` is viewed, the chart plots the x-axis time based on the comparison line (first in its series). This means you get the full scope of today's time. Whereas, if the primary line came first, the time in the x-axis only goes up to the current time of today. 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/6186705/197855806-0ad0b920-0523-481c-ab6f-1b9559648ac0.png">

In our report view, the primary line comes before the comparison, but it seems like there was a workaround to make sure the entire timeframe of the day gets plotted by adding zero values for the remainder of the time we haven't reached yet. This should not be the case as the data technically isn't at zero.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/6186705/197856363-7db6dfad-05b6-4d05-9b01-abdb2a71af58.png">

In addition to this, our bar charts also show the comparison bar before the primary bar. The primary data should always take precedence over the comparison and be ordered first. It's also confusing that the legend is showing the primary bar first.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/6186705/197856762-c0c4ec9c-c019-479f-9776-630d8a3363df.png">

cc @blboyle @mirualves @adamperron 
---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-viz/blob/main/CONTRIBUTING.md) for more information.

**Comment by envex** [comment]
Hello!

polaris-viz renders the data in the order it’s provided. If you want the comparison data to render after the other data, it needs to come last in the data array.

```
export const DEFAULT_DATA = [
  {
    name: 'Apr 1 – Apr 14, 2020',
    data: [
      {value: 333, key: '2020-04-01T12:00:00'},
    ],
  },
  {
    name: 'Previous month',
    data: [
      {value: 709, key: '2020-03-02T12:00:00'},
    ],
    isComparison: true,
  },
];
```

**Comment by blboyle** [comment]
@envex 

Let me know if you see this, but this is the issue that we were running into with the ordering of series.

https://codesandbox.io/s/agitated-tu-ygfn6n?file=/src/App.js

When the shorter-length series is first, the x-axis only goes to its length.
