### ISSUE TITLE
Increase visibility/accessibility of past comparison data line

### ISSUE THREAD

**Issue by chris-shopify** [Shopify/polaris-viz#1413]
The UX team is currently working on guidelines for dark and light modes and updating the visual language of the analytics elements (including updating the dark theme on reports to light mode). 

With the update on the Overview dashboard, it became more apparent that we have an issue with the viability of the past comparison line on light mode. We need to remove the opacity and increase the density between the dots.

![Image](https://user-images.githubusercontent.com/65421296/198348447-e86a92ad-6ef9-4b0c-9084-ad864afae10a.png)

![Image](https://user-images.githubusercontent.com/65421296/198348493-57026683-941e-425e-bb1e-b903b32a7d7b.png)

Here’s a visual comparison of what that would look like:

![Image](https://user-images.githubusercontent.com/65421296/198348549-132755df-19dd-48b8-8057-ef83d90520eb.png)

**Comment by LBWright** [comment]
@chris-shopify  Is the desired change specifically for light mode?

**Comment by chris-shopify** [comment]
Yes I believe so. In light mode the dots are too far apart for continuity.

@mirualves to confirm

**Comment by mirualves** [comment]
For both dark and light modes:
Light: #6793CC (103,147,204, 1)
Dark: #90B0DF (144,176,223, .8)

<img width="1183" alt="Screen Shot 2022-10-28 at 8 41 28 AM" src="https://user-images.githubusercontent.com/5349023/198589207-5ec2276b-686c-4857-8cbd-0edbe4cd15da.png">

<img width="670" alt="Screen Shot 2022-10-28 at 8 30 31 AM" src="https://user-images.githubusercontent.com/5349023/198587305-249ed358-f231-4fb9-aa98-bc1e2993cf15.png">
