### ISSUE TITLE
Misuse of zero states when we should use empty state

### ISSUE THREAD

**Issue by chris-shopify** [Shopify/polaris-viz#1415]
The chart below shows the data of "Today," and anything after around 12 pm (the time this screenshot was created) should be an empty state and not show zeros when time has not passed yet.

![Image](https://user-images.githubusercontent.com/65421296/198349089-de7c666e-11bc-4378-8d79-a598eb6c4869.png)

**Comment by blboyle** [comment]
@chris-shopify I will close this issue as the problem is the manner in which the consumer is using it. See linked issue.
