### ISSUE TITLE
Consistent line breaks across x-axis

### ISSUE THREAD

**Issue by pbojinov** [Shopify/polaris-viz#1418]
## Feature request summary

In the [ShopifyQL Notebooks - friction log](https://share.descript.com/view/V6GTaUmUXr3) video, Glen comes up across a couple scenarios where the x-axis with dates does not look consistent. It would be nice if we can detect that the x-axis items are dates and line break them all consistently or have them all by inline without any breaks.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/709616/198407295-3e9a8082-e1ea-4d81-adcf-69679ad5b084.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/709616/198407317-757e8860-efbc-409f-9998-b41cfb595d95.png">

## Rationale

This would be a UX improvement in the way dates are consistently displayed on the x-axis

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-viz/blob/main/CONTRIBUTING.md) for more information.

**Comment by envex** [comment]
Fixed as part of https://github.com/Shopify/polaris-viz/pull/1333
