### ISSUE TITLE
Prevent decimal numbers in yaxis

### ISSUE THREAD

**Issue by gil--** [Shopify/polaris-viz#1535]
## Feature request summary

Currently, Polaris charts show decimals in the yaxis even if no source data is in decimal form. An example is views where you'll never have 1.5 views but the y-axis still shows 0.5 or 1.5. 

Would be great if there was a simple way to easily force whole numbers on the yaxis via `yAxisOptions`. Currently if I round the values to the nearest whole, I get duplicates like 0, 1,1, 2, 2, etc.

### Example
<img width="635" alt="CleanShot 2023-05-23 at 12 58 52@2x" src="https://github.com/Shopify/polaris-viz/assets/3484527/9b786ac1-ea86-4836-afdd-3fc2860f2edd">

**Comment by envex** [comment]
@gil-- Can you try setting `integersOnly: true` in `yAxisOptions`?

```
yAxisOptions={{
   integersOnly: true
}}
```

**Comment by gil--** [comment]
@envex  Thanks that worked! Sorry I missed that in the documentation.

**Comment by envex** [comment]
All good, glad I could help!
