### ISSUE TITLE
[LineChart] Add animated transition between data changes

### ISSUE THREAD

**Issue by susiekims** [Shopify/polaris-viz#286]
We want to trigger the loading animations for the line chart if the data changes. Currently this is working as expected in web:

https://user-images.githubusercontent.com/30587540/115279169-5ad10e00-a114-11eb-83b6-7bc7241deb39.mp4

However, if we want to explore different transitions between data changes i.e. live updates with polling, we want to make sure that the animations are triggered when the `series.data` prop changes. 

For context, this works to trigger the animation:
![image](https://user-images.githubusercontent.com/30587540/115281401-f3688d80-a116-11eb-8297-7d9e45cc65c9.png)

but this does not:
![image](https://user-images.githubusercontent.com/30587540/115281468-0b401180-a117-11eb-8e18-c8c89f6f0344.png)
![image](https://user-images.githubusercontent.com/30587540/115281489-109d5c00-a117-11eb-9216-e5d065b97736.png)

This might be due to React using shallow equality to compare prop changes. Exploring a different transition (maybe the line continues to draw if more data points are added) is also an option.

### Acceptance Criteria
The line chart animation is re-triggered if the `data` property in any of the `series` changes.

**Comment by envex** [comment]
This is done: https://polaris-viz.shopify.com/?path=/story/polaris-viz-charts-linechart--dynamic-data
